apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: bdd-sbrp-import-1587317073
version: 0.1.0-SNAPSHOT
